site_name: Catatan Pribadi Agven M.R.
repo_url: https://github.com/pt.-artsys-integrasi-solusindo/gfk/odoo14c_gfk.git
nav:
    - Pendahuluan: index.md
    - Belajar:
        - Docker: 
            - Docker Dasar      : belajar/docker/01_base.md
            - Dockerfile        : belajar/docker/02_file.md
            - Docker Compose    : belajar/docker/03_compose.md
        - Monitoring: 
            - Prometheus        : belajar/monitoring/01_prometheus.md
            - Grafana           : belajar/monitoring/02_grafana.md
        - Ansible: 
            - Ansible Dasar     : belajar/ansible/01_base.md
            - Ansible Inventory : belajar/ansible/02_inventory.md
            - Ansible Playbook  : belajar/ansible/03_playbook.md
            - Ansible Role      : belajar/ansible/04_role.md
        - Next JS:
            - Next Dasar        : belajar/next/01_base.md
    - Catatan:
        - About                 : catatan/about.md
        - Technical             : catatan/technical.md
theme: 
    name: readthedocs
    custom_dir: custom_theme
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - zsh
extra_css:
    - assets/css/extra_css.css
    - assets/css/copy_code.css
extra_javascript:
    - assets/js/clipboard.min.js
    - assets/js/copy_code.js
markdown_extensions:
    - admonition
    - attr_list
plugins:
    - search
