site_name: Agven Muharis Rifqi
site_url: https://agvenmuharisrifqi.github.io/my_documentation
site_author: Agven Muharis Rifqi
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

repo_name: agvenmuharisrifqi/my_documentation
repo_url: https://github.com/agvenmuharisrifqi/my_documentation
edit_uri: /main/docs/

copyright: Copyright &copy; Oct 2024 - Now Agven Muharis Rifqi

theme: 
  name: material
  language: id
  custom_dir: overrides
  favicon: assets/img/mylogo.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - content.tooltips
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: indigo
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
      text: Roboto
      code: Roboto Mono

extra_css:
  - assets/css/home.css

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - tables
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: agvenmuharisrifqi
      repo: my_documentation
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.blocks.caption
  - toc:
      permalink: true

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  repo:
    facts:
      - latest
      - stars
      - forks
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agvenmuharisrifqi
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/agvenmuharisrifqi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/agven-muharis-rifqi-0008b81a0

nav:
  - Beranda: index.md
  - Belajar:
    - Container:
      - Docker            : belajar/container/docker.md
    - Virtualization:
      - Vagrant           : belajar/virtualization/vagrant.md
    - Provisioning:
      - Ansible           : belajar/provisioning/ansible.md
    - Monitoring: 
      - Prometheus        : belajar/monitoring/prometheus.md
      - Grafana           : belajar/monitoring/grafana.md
    - Load Testing: 
      - Locust            : belajar/load_testing/locust.md
    - ETL Tools:
      - Airbyte           : belajar/etl/airbyte.md
    - Server:
      - NAT VPS           : belajar/server/nat_vps.md
  - Catatan:
    - OpenVPN             : catatan/openvpn.md
    - About               : catatan/about.md
    - Technical           : catatan/technical.md
